name: Drata Remote

on:
  #push:
  #branches:
  #- '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # You fetch the current ref
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          runTests: npm run Electron
          #start: npm start
